# Generated by Django 5.2.1 on 2025-06-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="video_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на видео"
            ),
        ),
    ]
